export const SELECIONAR_CLIENTE = 'SELECIONAR_CLIENTE';
export const SELECIONAR_PRODUCTO = 'SELECIONAR_PRODUCTO';
export const CANTIDAD_PRODUCTO = 'CANTIDAD_PRODUCTO';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';