
'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './components/sidebar'
import { usePathname  } from 'next/navigation'; 
import { ApolloWrapper } from '@/lib/apollo';
import Header from './components/Header';
import PedidoState from '@/context/pedidos/PedidoState';
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'CMR-Dragon',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {
  const router = usePathname ();  

  return (
    <html lang="en">
    
      <body className={inter.className}>
      {router === '/login' || router === '/registro' ? (
        <div className='bg-gray-800 min-h-screen flex flex-col justify-center'>
          <div>
          <ApolloWrapper>{children}</ApolloWrapper>
          </div>
        </div>

      ):(
        <div className='bg-gray-200 min-h-screen'>
          <div className='flex min-h-screen'>
          <Sidebar />
         <main className='sm:w-2/3 xl:w-4/5 sm:min-h-screen p-5'>
         <ApolloWrapper>
         <PedidoState>
         <Header />
          {children}
          </PedidoState>
          </ApolloWrapper>

         </main>
          </div>
        </div>

      )}

        </body>
    </html>
  )
}
